name: Update README2

on:
  schedule:
        - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.4.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update README with recent activity
        uses: Alejoox/Alejoox-munevardavidalejandro@gmail.com # Reemplaza con tu información
